// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { setup } from "@skyra/env-utilities";
import { join } from "path";
import { defineConfig } from "prisma/config";

setup({ path: join(process.cwd(), ".env") });

export default defineConfig({
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
